# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: presigner-v2 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "presigner-v2"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Sota Yamashita"]
  s.date = "2015-03-24"
  s.description = "This gem create unsigned url S3 with version 2 of AWS SDK for Ruby. This gem is too small"
  s.email = "sota.yamashita@gmail.com"
  s.executables = ["presigner"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".travis.yml",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/presigner",
    "lib/presigner.rb",
    "presigner-v2.gemspec",
    "presigner_v2.gemspec",
    "spec/presigner_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/sotayamashita/presigner"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.6"
  s.summary = "Create unsigned url for S3"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 2.8.0", "~> 2.8"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, [">= 2.0.1", "~> 2.0"])
      s.add_development_dependency(%q<simplecov>, ["~> 0"])
      s.add_development_dependency(%q<aws-sdk>, ["~> 2"])
      s.add_development_dependency(%q<thor>, ["~> 0.19.1"])
    else
      s.add_dependency(%q<rspec>, [">= 2.8.0", "~> 2.8"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, [">= 2.0.1", "~> 2.0"])
      s.add_dependency(%q<simplecov>, ["~> 0"])
      s.add_dependency(%q<aws-sdk>, ["~> 2"])
      s.add_dependency(%q<thor>, ["~> 0.19.1"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 2.8.0", "~> 2.8"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, [">= 2.0.1", "~> 2.0"])
    s.add_dependency(%q<simplecov>, ["~> 0"])
    s.add_dependency(%q<aws-sdk>, ["~> 2"])
    s.add_dependency(%q<thor>, ["~> 0.19.1"])
  end
end

